baseURL: 'https://gregoryamcmullen.com'
title: "Greg McMullen"
pagination.pagerSize: 10
theme: hugo-PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-8961898-1

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: About
          url: /about/
        - name: Code
          url: /code/
        - name: Posts
          url: /posts/

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "Greg McMullen"
  description: 'Husband. Dad. Swim Coach. Web Dev.'
  author: "Greg McMullen"
  # author: ["Me", "You"] # multiple authors

  # images: "<link or path of image for opengraph, twitter-cards>"

  ShowReadingTime: false
  ShowShareButtons: false
  comments: false
  defaultTheme: dark
  disableThemeToggle : false
  disableSpecial1stPost : false

  assets:
#     favicon: '<path / external url>'

  label:
    text: "> $ cd ~/"
#     icon: /apple-touch-icon.png
#     iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Greg McMullen"
    # imageUrl: '<img location>'
    # imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Projects
        url: code

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: "Welcome to my blog"

  socialIcons:
    - name: linkedin
      url: 'https://www.linkedin.com/in/gregmcmullen'
    - name: github
      url: 'https://github.com/mcmullengreg'

  analytics:
    google:
     SiteVerificationTag: "EJ9fXIvA3S8Fy7MpudnG8k1vJMtx_lODn198G5ODEjM"